[build]
  command = "cd taskwise && npm install react-scripts && npm run build"
  publish = "taskwise/build"  # Adjust this if the publish directory is different

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200